//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursProj.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int id { get; set; }
        public string article { get; set; }
        public string name { get; set; }
        public int yearOfPublic { get; set; }
        public string description { get; set; }
        public int authorID { get; set; }
        public int genreID { get; set; }
        public int publishID { get; set; }
        public int stateID { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Genres Genres { get; set; }
        public virtual PublishingHouse PublishingHouse { get; set; }
        public virtual State State { get; set; }
        public virtual UserBookPair UserBookPair { get; set; }
    }
}
